# Setup a cache to cache job parts between jobs to ensure faster builds
cache:
    key: "$CI_JOB_NAME"
    untracked: true
    paths:
    - $HOME/.cargo/
    - target/

# Set any required environment variables here
variables:
  RUST_BACKTRACE: "FULL"

image: "rust:latest"

stages:
- test

check:
  stage: test
  before_script:
    - rustup component add rustfmt clippy
    - cargo install cargo-audit
  script:
    - cargo check --verbose
    # - cargo fmt -- --check # GAT 사용하면 fmt 수행시 컴파일이 안 됨
    - cargo clippy -- -D warnings
    - cargo audit

debug:
  stage: test
  script:
    - rm -f test/* # pool layout 바뀔 때마다 기존 파일을 직접 제거해야하는 불편함 해소
    - RUST_MIN_STACK=1073741824 cargo test # 테스트시 Op들을 정적할당하기 위해 Stack 크기가 커야함

release:
  stage: test
  script:
    - rm -f test/*
    - RUST_MIN_STACK=1073741824 cargo test --release
