[package]
name = "compositional-persistent-object"
version = "0.1.0"
authors = [
    "Kyeongmin Cho <kyeongmin.cho@kaist.ac.kr>",
    "Seungmin Jeon <seungmin.jeon@kaist.ac.kr>",
    "Jeehoon Kang <jeehoon.kang@kaist.ac.kr>"
]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["use_clwb"]
no_persist = []
use_clflushopt = []
use_clwb = []
use_msync = []
stat_print_flushes = []

[dependencies]
crossbeam-epoch = "0.9.5"
crossbeam-utils = "0.8.5"
# chrono = "0.4" # TODO: chrono crate의 audit 이슈 해결되면 사용 https://github.com/chronotope/chrono/pull/578#issuecomment-945604623
etrace = "1.1.1"
memmap = "0.7.0"
rand = "0.8.4"
tempfile = "3.2.0"
array-init = "2.0.0"
regex = "1.5.4"
structopt = "0.3"
csv = "1.1.6"
corundum = "0.4.0"

[dev-dependencies]
log = "0.4.14"
env_logger = "0.9.0"
serial_test = "0.5.1"
