[package]
name = "memento"
version = "0.1.0"
authors = [
    "Kyeongmin Cho <kyeongmin.cho@kaist.ac.kr>",
    "Seungmin Jeon <seungmin.jeon@kaist.ac.kr>",
    "Jeehoon Kang <jeehoon.kang@kaist.ac.kr>"
]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["use_clwb"]
no_persist = []
use_clflushopt = []
use_clwb = []
use_msync = []
stat_print_flushes = []

[dependencies]
crossbeam-epoch = { git = "https://cp-git.kaist.ac.kr/persistent-mem/crossbeam-memento/", package = "crossbeam-epoch", branch = "old_guard" }
crossbeam-utils = "0.8.5"
chrono = "0.4"
etrace = "1.1.1"
rand = "0.8.4"
tempfile = "3.2.0"
array-init = "2.0.0"

[dev-dependencies]
log = "0.4.14"
env_logger = "0.9.0"
serial_test = "0.5.1"
