[package]
name = "compositional-persistent-object"
version = "0.1.0"
authors = [
    "Kyeongmin Cho <kyeongmin.cho@kaist.ac.kr>",
    "Seungmin Jeon <seungmin.jeon@kaist.ac.kr>",
    "Jeehoon Kang <jeehoon.kang@kaist.ac.kr>"
]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-epoch = "0.9.5"
crossbeam-utils = "0.8.5"
chrono = "0.4"
etrace = "1.1.1"
memmap = "0.7.0"
rand = "0.8.4"
tempfile = "3.2.0"

[dev-dependencies]
log = "0.4.14"
env_logger = "0.9.0"
serial_test = "0.5.1"
