[package]
name = "compositional-persistent-object"
version = "0.1.0"
authors = ["Kyeongmin Cho <kyeongmin.cho@kaist.ac.kr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
