[package]
name = "crossbeam-channel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-queue = "0.3.0"
crossbeam-utils = { path = "../crossbeam-utils" }
atomic = "0.5"
